; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:4d_systems_esp32s3_gen4_r8n16]
platform = espressif32
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
board_build.flash_size = 16MB
build_flags = 
	-I lib/lvgl
	-D LV_LVGL_H_INCLUDE_SIMPLE
	-Os
lib_deps = 
	dfrobot/DFRobot_SHT20@^1.0.0
	paulstoffregen/OneWire@^2.3.8
	milesburton/DallasTemperature@^4.0.5
	esphome/ESP32-audioI2S@^2.3.0
	bblanchon/ArduinoJson@^7.4.2
	